function esc(text) {
  return String(text ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function formatPrice(value) {
  return `Rs ${Number(value || 0).toFixed(2)}`;
}

function line(text, x, y, size = 10) {
  return `BT /F1 ${size} Tf ${x} ${y} Td (${esc(text)}) Tj ET`;
}

/**
 * Builds a compact single-document PDF as a Blob.
 *
 * Kept data-only so the same report model can later be passed to an email
 * delivery service or moved server-side without changing the report page.
 *
 * @param {object} report
 * @returns {Blob}
 */
export function buildReportPdf(report) {
  const rows = [];
  rows.push(line('MedPrice Medicine Savings Report', 48, 790, 18));
  rows.push(line(`Date: ${new Date(report.summary.generatedAt).toLocaleDateString('en-IN')}`, 48, 765, 10));
  rows.push(line(`Current total: ${formatPrice(report.summary.currentTotal)}`, 48, 735, 11));
  rows.push(line(`Cheapest total: ${formatPrice(report.summary.cheapestTotal)}`, 48, 718, 11));
  rows.push(line(`Savings: ${formatPrice(report.summary.totalSavings)} (${Number(report.summary.savingsPercentage || 0).toFixed(1)}%)`, 48, 701, 11));
  rows.push(line(`Generic savings opportunity: ${formatPrice(report.summary.genericSavings)}`, 48, 684, 11));
  rows.push(line(`NPPA violations: ${report.summary.nppaViolationCount}`, 48, 667, 11));

  let y = 632;
  rows.push(line('Pharmacy comparison', 48, y, 13));
  y -= 18;
  for (const pharmacy of report.pharmacies || []) {
    rows.push(line(`${pharmacy.winner ? '* ' : ''}${pharmacy.name}: ${formatPrice(pharmacy.total)} | ${pharmacy.availableCount} available, ${pharmacy.unavailableCount} unavailable`, 56, y, 9));
    y -= 14;
  }

  y -= 12;
  rows.push(line('Medicines', 48, y, 13));
  y -= 18;
  for (const item of (report.medicines || []).slice(0, 22)) {
    rows.push(line(`${item.medicine.brand_name}: ${item.selectedPharmacy || 'Unavailable'} ${formatPrice(item.selectedPrice)} | Generic: ${item.generic?.brand_name || '-'} ${formatPrice(item.genericPrice)} | NPPA: ${item.nppaStatus}`, 56, y, 8));
    y -= 13;
  }

  rows.push(line('Generated by MedPrice', 48, 40, 9));

  const stream = rows.join('\n');
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${stream.length} >> stream\n${stream}\nendstream endobj`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (const object of objects) {
    offsets.push(pdf.length);
    pdf += `${object}\n`;
  }

  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
}
